### ISSUE TITLE
Crashing with sewer generation

### ISSUE THREAD

**Issue by Huntert2017** [Patrigan/SlimierSlimes#14]
Hello, I am running the most recent version of slimier slimes and our server is crashing when navigating to a specific chunk in the world. I have attached the crash log. 
[crash-2021-09-30_15.44.14-server.txt](https://github.com/Patrigan/SlimierSlimes/files/7264142/crash-2021-09-30_15.44.14-server.txt)

**Comment by Patrigan** [comment]
I know this is late, but the issue was at the Caves And Cliffs backport. I took it up with them and they released a fix in a newer version.
