### ISSUE TITLE
Compability with SlimyBoyos

### ISSUE THREAD

**Issue by crafting-Aaron** [Patrigan/SlimierSlimes#3]
It would be fun if the colored slimes are also able to pick up items and not just the vanilla green ones. Could you also add a config option for slimes to spawn on the surface occasionally? To give that classic rpg common enemy feel.

**Comment by Patrigan** [comment]
I have had a chat with the developer of SlimyBoyos and I should be able to work in compatibility. for the 1.1.0 version It looks easy enough.

I will eventually replace it with my own system, as I'm not a huge fan of the way he renders them. But I'll ensure lasting compatibility, so you could decide to keep both mods active.

**Comment by Patrigan** [comment]
Compatibility finished. Will wrap up testing and complete the current version 1.1.0 and then you should be able to see slimes picking up items.
