### ISSUE TITLE
Some vanilla dye recipes are gone

### ISSUE THREAD

**Issue by RealDovahbear** [Patrigan/SlimierSlimes#5]
You can't craft bone meal, ink sacs, lapis lazuli, or cocoa beans into their respective dyes, and cactus can't be smelted into green dye. This doesn't affect vanilla flowers, however.

**Comment by Patrigan** [comment]
Confirmed not working, I have an inkling of what this problem might be, but I'm gonna have to throw a bone at it.

**Comment by RealDovahbear** [comment]
This has now been fixed, thank you!

**Comment by Patrigan** [comment]
you're welcome!
