### ISSUE TITLE
Cannot update from 1.0.4 to 1.1.0 or 1.1.1 (1.16.5 Forge 36.0.45)

### ISSUE THREAD

**Issue by FurryApocalypse** [Patrigan/SlimierSlimes#6]
Dont know why i have issue when i try to update mod on the server.
I dont have crash report couse the problem occurs while world is loading mods and there are no crash reports left :C 
Version 1.0.4 still works.
Just in case - singleplayer works fine
I tried to delete serverconfig with no succes - in fact no new serverconfig was created after i deleted last one

**Comment by Patrigan** [comment]
Good news, I already had reports about some server issues. I am working on fixing them asap, expect a fix in the next couple days :)

**Comment by FurryApocalypse** [comment]
Great! Can't wait :D
I'll be looking for upcoming update then <3

**Comment by Patrigan** [comment]
1.1.2 should fix your issues. It is now sent for approval to curseforge :)
